/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/10.1.44 (10.1.1)
 * Generated at: 2025-08-30 06:37:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <title>Interfaces</title>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("  <meta name=\"robots\" content=\"index,follow\">\n");
      out.write("  <meta name=\"generator\" content=\"GrapesJS Studio\">\n");
      out.write("  <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("  <link rel=\"stylesheet\" href=\"./styles/index.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body id=\"iqn6\" class=\"gjs-t-body cls-89x28j\">\n");
      out.write("  <section id=\"ibw5z\" class=\"gjs-section\">\n");
      out.write("    <div id=\"im6i6\" class=\"gjs-container\">\n");
      out.write("      <div data-type-role=\"flex-row\" id=\"iowu7\" class=\"gjs-plg-flex-row\">\n");
      out.write("        <div data-type-role=\"flex-column\" id=\"i987k\" class=\"gjs-plg-flex-column\">\n");
      out.write("          <h1 id=\"ibz1v\"><b>Diseño de Interfaces</b></h1>\n");
      out.write("        </div>\n");
      out.write("        <div data-type-role=\"flex-column\" id=\"ifw75\" class=\"gjs-plg-flex-column\">\n");
      out.write("          <div data-type-role=\"flex-row\" id=\"iol48\" class=\"gjs-plg-flex-row\">\n");
      out.write("            <div data-type-role=\"flex-column\" id=\"i4zt5\" class=\"gjs-plg-flex-column\">\n");
      out.write("              <div id=\"ilcv1\">\n");
      out.write("                <div id=\"ioowz\"><span data-gs-mrk-fs=\"true\" id=\"i0mu2\">Usuario</span></div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div data-type-role=\"flex-column\" id=\"isqw9\" class=\"gjs-plg-flex-column\">\n");
      out.write("              <div id=\"il8df\">\n");
      out.write("                <div id=\"iy1hy\"><span data-gs-mrk-fs=\"true\" id=\"i2iyh\">Salir</span></div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  <section id=\"ia3cg\" class=\"gjs-section\">\n");
      out.write("    <div id=\"i46bl\" class=\"gjs-container\">\n");
      out.write("      <div data-type-role=\"flex-row\" id=\"ixadv\" class=\"gjs-plg-flex-row\">\n");
      out.write("        <div data-type-role=\"flex-column\" id=\"itmu3\" class=\"gjs-plg-flex-column\">\n");
      out.write("          <div data-type-role=\"flex-row\" id=\"i1zm1\" class=\"gjs-plg-flex-row\">\n");
      out.write("            <div data-type-role=\"flex-column\" id=\"i1c4x\" class=\"gjs-plg-flex-column\">\n");
      out.write("              <div id=\"ihtuv\">\n");
      out.write("                <div id=\"i3fsi\">Menú</div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div data-type-role=\"flex-column\" id=\"i8y3i\" class=\"gjs-plg-flex-column\">\n");
      out.write("              <div id=\"i7tkp\"><a href=\"registroUsuario.jsp\" target=\"iframe-contenido\" class=\"gjs-t-link\" id=\"iok6r\">Registro de Usuarios</a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div data-type-role=\"flex-column\" id=\"i9ebk\" class=\"gjs-plg-flex-column\">\n");
      out.write("              <div id=\"icqa3\"><a href=\"reporte.jsp\" target=\"iframe-contenido\" class=\"gjs-t-link\" id=\"iv1q1\">Reporte</a></div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div data-type-role=\"flex-column\" id=\"i3hao\" class=\"gjs-plg-flex-column\"><iframe frameborder=\"0\"\n");
      out.write("            id=\"iframe-contenido\" name=\"iframe-contenido\" src=\"frontPrincipal.jsp\" title=\"Contenido principal\" loading=\"lazy\" allowfullscreen=\"\">\n");
      out.write("          </iframe></div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
