#!/usr/bin/env bash
#
# Generates every secret the local stack needs and prints a complete .env to stdout.
#
#   cd app/backend/microservices
#   ../../../scripts/generate-dev-secrets.sh [stack] > .env
#
# `stack` names the checkout this .env belongs to - back (default), front, swift, kotlin. It
# becomes KAPP_STACK, which names the Compose project, the containers and the image tags, so
# two worktrees can run at once without taking each other's names, ports or images.
#
# The secrets are generated ON THIS MACHINE and never leave it. That is the point: a
# password pasted into a chat, an issue or a commit stays in that history forever, and
# rotating it later does not remove it from there.
#
# Re-running produces a different set. If the Mongo volume already holds users created
# with the old passwords, the container will refuse to authenticate and say so — recover
# with `docker compose --profile full down -v`, which discards the local data.
#
set -euo pipefail

STACK="${1:-back}"

# 32 alphanumeric characters. Deliberately no symbols: these end up inside MongoDB
# connection strings, where '@', ':', '/' and '?' are delimiters and would have to be
# percent-encoded. Length carries the entropy instead.
#
# The subshell disables pipefail for this pipeline only. `head -c` closes the pipe as soon
# as it has enough bytes, `tr` dies of SIGPIPE, and under `set -o pipefail` that makes the
# whole function fail — silently producing an empty password.
secret() {
  ( set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${1:-32}" )
}

ROOT_PW=$(secret)
AUTH_PW=$(secret)
USER_PW=$(secret)
SEMAPHORE_PW=$(secret)
SCHEDULE_PW=$(secret)
MAP_PW=$(secret)
INTERNAL_TOKEN=$(secret 48)
JWT_KEY_ID="kapp-$(date +%Y%m)"

cat <<EOF
# Generated by scripts/generate-dev-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# LOCAL DEVELOPMENT ONLY. Never commit this file — .gitignore already excludes it.
# Rotate everything here before the stack is reachable from outside a laptop.

# ── MongoDB ────────────────────────────────────────────────────────────────────
MONGO_ROOT_USER=kapp_root
MONGO_ROOT_PASSWORD=${ROOT_PW}

MONGO_AUTH_PASSWORD=${AUTH_PW}
MONGO_USER_PASSWORD=${USER_PW}
MONGO_SEMAPHORE_PASSWORD=${SEMAPHORE_PW}
MONGO_SCHEDULE_PASSWORD=${SCHEDULE_PW}
MONGO_MAP_PASSWORD=${MAP_PW}

# One connection string per service. Each user lives in the database it owns, so that
# database is also its authSource and a leaked credential opens only that one.
#
# SINGLE-QUOTED, and that matters. These contain '&', and a shell sourcing this file with
# `. .env` reads an unquoted one as "assign up to the &, then run the rest in background" -
# leaving the variable EMPTY. Docker Compose has its own parser and does not care, which is
# what makes the bug invisible: the services connect fine and only the scripts break.#
# maxPoolSize=10 is not arbitrary. An M0 cluster allows 500 concurrent connections and the
# driver's default pool is 100 PER SERVICE - the services is 500 for one developer, and six
# developers sharing the cluster could ask for 3000. The pool only grows under load, so this
# has never bitten us, which is exactly why it would bite at the worst possible moment. Six
# developers times the services times ten is 300, with room to spare, and ten connections is
# far more than a development service ever needs.
MONGO_AUTH_URI='mongodb://kapp_auth_user:${AUTH_PW}@mongo:27017/kapp_auth?replicaSet=rs0&authSource=kapp_auth&maxPoolSize=10'
MONGO_USER_URI='mongodb://kapp_user_user:${USER_PW}@mongo:27017/kapp_user?replicaSet=rs0&authSource=kapp_user&maxPoolSize=10'
MONGO_SEMAPHORE_URI='mongodb://kapp_semaphore_user:${SEMAPHORE_PW}@mongo:27017/kapp_semaphore?replicaSet=rs0&authSource=kapp_semaphore&maxPoolSize=10'
MONGO_SCHEDULE_URI='mongodb://kapp_schedule_user:${SCHEDULE_PW}@mongo:27017/kapp_schedule?replicaSet=rs0&authSource=kapp_schedule&maxPoolSize=10'
MONGO_MAP_URI='mongodb://kapp_map_user:${MAP_PW}@mongo:27017/kapp_map?replicaSet=rs0&authSource=kapp_map&maxPoolSize=10'

# ── Services ───────────────────────────────────────────────────────────────────
# Shared secret for POST /internal/users, the one call auth-service makes to
# user-service during registration, when no user token exists yet.
KAPP_INTERNAL_TOKEN=${INTERNAL_TOKEN}

KAPP_JWT_KEY_ID=${JWT_KEY_ID}
KAPP_STACK=${STACK}
KAPP_REQUIRE_EMAIL_VERIFICATION=false
KAPP_LOG_LEVEL=INFO
EOF

cat >&2 <<'EOF'

Written. Two things worth knowing:

  1. These are local development secrets. They are not shared with your teammates —
     each machine generates its own — and they must be rotated before anything is
     reachable from outside.

  2. To point at Atlas instead, replace the five MONGO_*_URI values with the cluster's
     strings — mongodb+srv://..., with neither replicaSet nor authSource — and run
     `docker compose --profile cloud up -d`, which starts no local database.
     Step by step: docs/ATLAS-SETUP.md

EOF
