#!/usr/bin/env bash
#
# Prints a starting .env for the stack: everything it can generate, and a named blank for
# everything only the Atlas cluster can give you.
#
#   cd app/backend/microservices
#   ../../../scripts/generate-dev-secrets.sh [stack] > .env
#
# `stack` names the checkout this .env belongs to - back (default), front, swift, kotlin. It
# becomes KAPP_STACK, which names the containers and the image tags, so two worktrees can run
# at once without taking each other's names, ports or images.
#
# THE DATABASE IS NOT GENERATED HERE. There is no local MongoDB any more: the five
# MONGO_*_URI values come from the shared Atlas cluster, one per service, and you paste them
# in. docs/ATLAS-SETUP.md is the walkthrough; a teammate who already has them can send you
# theirs over a private channel, never through the group chat or a commit.
#
# What IS generated here is generated ON THIS MACHINE and never leaves it. That is the point:
# a secret pasted into a chat, an issue or a commit stays in that history forever, and
# rotating it later does not remove it from there.
#
set -euo pipefail

STACK="${1:-back}"

# 48 alphanumeric characters. Deliberately no symbols: this travels in HTTP headers and
# shell variables, where quoting mistakes are silent.
#
# The subshell disables pipefail for this pipeline only. `head -c` closes the pipe as soon
# as it has enough bytes, `tr` dies of SIGPIPE, and under `set -o pipefail` that makes the
# whole function fail — silently producing an empty secret.
secret() {
  ( set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${1:-32}" )
}

INTERNAL_TOKEN=$(secret 48)
JWT_KEY_ID="kapp-$(date +%Y%m)"

cat <<EOF
# Generated by scripts/generate-dev-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# DEVELOPMENT ONLY. Never commit this file — .gitignore already excludes it.

# ── The shared Atlas cluster ───────────────────────────────────────────────────
# One connection string per service, each with its own account: the account can read and
# write ONE database, so a credential that leaks opens only that service's data. Get them
# from docs/ATLAS-SETUP.md or from a teammate, and paste them below. The stack refuses to
# start while they are empty, which is the point — there is nothing local to fall back to.
#
# SINGLE-QUOTE them, and that matters. They contain '&', and a shell sourcing this file
# with \`. .env\` reads an unquoted one as "assign up to the &, then run the rest in
# background" - leaving the variable EMPTY. Docker Compose has its own parser and does not
# care, which is what makes the bug invisible: the services connect fine and only the
# scripts break.
#
# Keep maxPoolSize=10 on each one. An M0 cluster allows 500 concurrent connections and the
# driver's default pool is 100 PER SERVICE - five services is 500 for one developer, and six
# developers sharing the cluster could ask for 3000. The pool only grows under load, so this
# has never bitten us, which is exactly why it would bite at the worst possible moment.
MONGO_AUTH_URI=''
MONGO_USER_URI=''
MONGO_SEMAPHORE_URI=''
MONGO_SCHEDULE_URI=''
MONGO_MAP_URI=''

# ── Services ───────────────────────────────────────────────────────────────────
# Shared secret for POST /internal/users, the one call auth-service makes to
# user-service during registration, when no user token exists yet.
KAPP_INTERNAL_TOKEN=${INTERNAL_TOKEN}

KAPP_JWT_KEY_ID=${JWT_KEY_ID}
KAPP_STACK=${STACK}
KAPP_REQUIRE_EMAIL_VERIFICATION=false
KAPP_LOG_LEVEL=INFO
EOF

cat >&2 <<'EOF'

Written. Two things worth knowing:

  1. It is not usable yet: paste the five MONGO_*_URI values from the Atlas cluster.
     docs/ATLAS-SETUP.md walks through where they come from.

  2. KAPP_INTERNAL_TOKEN was generated on this machine and is yours alone. Every service in
     YOUR stack shares it, and it must be rotated before anything is reachable from outside.

EOF
